apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: k8s-cluster-01
  namespace: dev
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: container-vsan-data
    workers:
      count: 1
      class: best-effort-xsmall
      storageClass: container-vsan-data
  settings:
    storage:
      classes: ["container-vsan-data"]
      defaultClass: container-vsan-data
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]


